/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.docs.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Test service. Represents a row in the &quot;TEST_Test&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.test.model.impl.TestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.test.model.impl.TestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Test
 * @generated
 */
@ProviderType
public interface TestModel
	extends BaseModel<Test>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test model instance should use the {@link Test} interface instead.
	 */

	/**
	 * Returns the primary key of this test.
	 *
	 * @return the primary key of this test
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test.
	 *
	 * @param primaryKey the primary key of this test
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this test.
	 *
	 * @return the uuid of this test
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this test.
	 *
	 * @param uuid the uuid of this test
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the foo ID of this test.
	 *
	 * @return the foo ID of this test
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this test.
	 *
	 * @param fooId the foo ID of this test
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the group ID of this test.
	 *
	 * @return the group ID of this test
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this test.
	 *
	 * @param groupId the group ID of this test
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this test.
	 *
	 * @return the company ID of this test
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this test.
	 *
	 * @param companyId the company ID of this test
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this test.
	 *
	 * @return the user ID of this test
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this test.
	 *
	 * @param userId the user ID of this test
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this test.
	 *
	 * @return the user uuid of this test
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this test.
	 *
	 * @param userUuid the user uuid of this test
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this test.
	 *
	 * @return the user name of this test
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this test.
	 *
	 * @param userName the user name of this test
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this test.
	 *
	 * @return the create date of this test
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this test.
	 *
	 * @param createDate the create date of this test
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this test.
	 *
	 * @return the modified date of this test
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this test.
	 *
	 * @param modifiedDate the modified date of this test
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Test cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}